// <auto-generated />
namespace UCRMS_Version2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Version7AddedGradeModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version7AddedGradeModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201605081909320_Version7-AddedGradeModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
