// <auto-generated />
namespace UCRMS_Version2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Version2MadeTeacherIdPropertyNullableInCourseModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version2MadeTeacherIdPropertyNullableInCourseModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201605051210182_Version2-MadeTeacherIdPropertyNullableInCourseModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
